name: Generate Database Diagram
on:
  pull_request: 
    branches:
      - master
  push:
    paths: 
      - ./src/AnimalTrack.Migrations/**
    branches:
      - master

env:
  DOTNET_VERSION: 8.x.x

jobs:
  generate-db-diagram:
    runs-on: ubuntu-22.04
    
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: WhatTheFooBar123
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup dotnet ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 14.15.0
          
      - name: Run Migrations
        working-directory: src/AnimalTrack.Migrations
        run: dotnet run

      - name: Install pg-mermaid
        run: npm install -g pg-mermaid --save-dev "tslib@2.5.0"
        
      - name: Generate Diagram
        run: pg-mermaid --dbname AnimalTrack --username postgres --password WhatTheFooBar123 --host 127.0.0.1 --port 5432 --output-path